id: I77722755
source: https://www.lotsawahouse.org
source_file: null
initial_creation_type: input
imported: '2022-05-31T05:13:26.787613'
last_modified: '2022-05-31T05:13:26.787620'
parser: null
source_metadata:
  title: Metrul Tendzin Gyatso Series
  language: bo
  description: Texts by Metrul Tendzin Gyatso (rme sprul bstan 'dzin rgya mtsho, b.
    1968)
  volume:
    f12A8:
      title: 'A River Filled with the Amṛta of Love: A Liturgy for Saving and Releasing
        the Lives of Animals'
      base_file: f12A8.txt
      order: 1
      parent: Saving Lives
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
